package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * BAvailableGames generated by hbm2java
 */
public class BAvailableGames implements java.io.Serializable {

	private BigDecimal BAvailableGamesId;
	private BStatus BStatus;
	private String nameOfGame;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public BAvailableGames() {
	}

	public BAvailableGames(BigDecimal BAvailableGamesId) {
		this.BAvailableGamesId = BAvailableGamesId;
	}

	public BAvailableGames(BigDecimal BAvailableGamesId, BStatus BStatus, String nameOfGame, Date createdDate,
			String createdBy, Date updatedDate, String updatedBy) {
		this.BAvailableGamesId = BAvailableGamesId;
		this.BStatus = BStatus;
		this.nameOfGame = nameOfGame;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public BigDecimal getBAvailableGamesId() {
		return this.BAvailableGamesId;
	}

	public void setBAvailableGamesId(BigDecimal BAvailableGamesId) {
		this.BAvailableGamesId = BAvailableGamesId;
	}

	public BStatus getBStatus() {
		return this.BStatus;
	}

	public void setBStatus(BStatus BStatus) {
		this.BStatus = BStatus;
	}

	public String getNameOfGame() {
		return this.nameOfGame;
	}

	public void setNameOfGame(String nameOfGame) {
		this.nameOfGame = nameOfGame;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
