package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BBooking generated by hbm2java
 */
public class BBooking implements java.io.Serializable {

	private BigDecimal BBookingId;
	private BStatus BStatus;
	private BUsers BUsers;
	private BGame BGame;
	private String bookedSlots;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private Set BPayments = new HashSet(0);

	public BBooking() {
	}

	public BBooking(BigDecimal BBookingId) {
		this.BBookingId = BBookingId;
	}

	public BBooking(BigDecimal BBookingId, BStatus BStatus, BUsers BUsers, BGame BGame, String bookedSlots,
			Date createdDate, String createdBy, Date updatedDate, String updatedBy, Set BPayments) {
		this.BBookingId = BBookingId;
		this.BStatus = BStatus;
		this.BUsers = BUsers;
		this.BGame = BGame;
		this.bookedSlots = bookedSlots;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.BPayments = BPayments;
	}

	public BigDecimal getBBookingId() {
		return this.BBookingId;
	}

	public void setBBookingId(BigDecimal BBookingId) {
		this.BBookingId = BBookingId;
	}

	public BStatus getBStatus() {
		return this.BStatus;
	}

	public void setBStatus(BStatus BStatus) {
		this.BStatus = BStatus;
	}

	public BUsers getBUsers() {
		return this.BUsers;
	}

	public void setBUsers(BUsers BUsers) {
		this.BUsers = BUsers;
	}

	public BGame getBGame() {
		return this.BGame;
	}

	public void setBGame(BGame BGame) {
		this.BGame = BGame;
	}

	public String getBookedSlots() {
		return this.bookedSlots;
	}

	public void setBookedSlots(String bookedSlots) {
		this.bookedSlots = bookedSlots;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getBPayments() {
		return this.BPayments;
	}

	public void setBPayments(Set BPayments) {
		this.BPayments = BPayments;
	}

}
