package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BGame generated by hbm2java
 */
public class BGame implements java.io.Serializable {

	private BigDecimal BGameId;
	private BStatus BStatus;
	private String nameOfGame;
	private String organizationName;
	private String location;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private Set BBookings = new HashSet(0);
	private Set BSlots = new HashSet(0);

	public BGame() {
	}

	public BGame(BigDecimal BGameId) {
		this.BGameId = BGameId;
	}

	public BGame(BigDecimal BGameId, BStatus BStatus, String nameOfGame, String organizationName, String location,
			Date createdDate, String createdBy, Date updatedDate, String updatedBy, Set BBookings, Set BSlots) {
		this.BGameId = BGameId;
		this.BStatus = BStatus;
		this.nameOfGame = nameOfGame;
		this.organizationName = organizationName;
		this.location = location;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.BBookings = BBookings;
		this.BSlots = BSlots;
	}

	public BigDecimal getBGameId() {
		return this.BGameId;
	}

	public void setBGameId(BigDecimal BGameId) {
		this.BGameId = BGameId;
	}

	public BStatus getBStatus() {
		return this.BStatus;
	}

	public void setBStatus(BStatus BStatus) {
		this.BStatus = BStatus;
	}

	public String getNameOfGame() {
		return this.nameOfGame;
	}

	public void setNameOfGame(String nameOfGame) {
		this.nameOfGame = nameOfGame;
	}

	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getBBookings() {
		return this.BBookings;
	}

	public void setBBookings(Set BBookings) {
		this.BBookings = BBookings;
	}

	public Set getBSlots() {
		return this.BSlots;
	}

	public void setBSlots(Set BSlots) {
		this.BSlots = BSlots;
	}

}
