package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * BPayment generated by hbm2java
 */
public class BPayment implements java.io.Serializable {

	private BigDecimal BPaymentId;
	private BStatus BStatus;
	private BBooking BBooking;
	private BigDecimal hours;
	private String gateway;
	private BigDecimal totalAmount;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public BPayment() {
	}

	public BPayment(BigDecimal BPaymentId) {
		this.BPaymentId = BPaymentId;
	}

	public BPayment(BigDecimal BPaymentId, BStatus BStatus, BBooking BBooking, BigDecimal hours, String gateway,
			BigDecimal totalAmount, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
		this.BPaymentId = BPaymentId;
		this.BStatus = BStatus;
		this.BBooking = BBooking;
		this.hours = hours;
		this.gateway = gateway;
		this.totalAmount = totalAmount;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public BigDecimal getBPaymentId() {
		return this.BPaymentId;
	}

	public void setBPaymentId(BigDecimal BPaymentId) {
		this.BPaymentId = BPaymentId;
	}

	public BStatus getBStatus() {
		return this.BStatus;
	}

	public void setBStatus(BStatus BStatus) {
		this.BStatus = BStatus;
	}

	public BBooking getBBooking() {
		return this.BBooking;
	}

	public void setBBooking(BBooking BBooking) {
		this.BBooking = BBooking;
	}

	public BigDecimal getHours() {
		return this.hours;
	}

	public void setHours(BigDecimal hours) {
		this.hours = hours;
	}

	public String getGateway() {
		return this.gateway;
	}

	public void setGateway(String gateway) {
		this.gateway = gateway;
	}

	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
