package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * BSlot generated by hbm2java
 */
public class BSlot implements java.io.Serializable {

	private BigDecimal BSlotId;
	private BStatus BStatus;
	private BGame BGame;
	private String slot1;
	private String slot2;
	private String slot3;
	private String slot4;
	private String slot5;
	private String slot6;
	private String slot7;
	private String slot8;
	private String slot9;
	private String slot10;
	private String slot11;
	private String slot12;
	private String slot13;
	private String slot14;
	private String slot15;
	private String slot16;
	private String slot17;
	private String slot18;
	private String slot19;
	private String slot20;
	private String slot21;
	private String slot22;
	private String slot23;
	private String slot24;
	private String available;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public BSlot() {
	}

	public BSlot(BigDecimal BSlotId) {
		this.BSlotId = BSlotId;
	}

	public BSlot(BigDecimal BSlotId, BStatus BStatus, BGame BGame, String slot1, String slot2, String slot3,
			String slot4, String slot5, String slot6, String slot7, String slot8, String slot9, String slot10,
			String slot11, String slot12, String slot13, String slot14, String slot15, String slot16, String slot17,
			String slot18, String slot19, String slot20, String slot21, String slot22, String slot23, String slot24,
			String available, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
		this.BSlotId = BSlotId;
		this.BStatus = BStatus;
		this.BGame = BGame;
		this.slot1 = slot1;
		this.slot2 = slot2;
		this.slot3 = slot3;
		this.slot4 = slot4;
		this.slot5 = slot5;
		this.slot6 = slot6;
		this.slot7 = slot7;
		this.slot8 = slot8;
		this.slot9 = slot9;
		this.slot10 = slot10;
		this.slot11 = slot11;
		this.slot12 = slot12;
		this.slot13 = slot13;
		this.slot14 = slot14;
		this.slot15 = slot15;
		this.slot16 = slot16;
		this.slot17 = slot17;
		this.slot18 = slot18;
		this.slot19 = slot19;
		this.slot20 = slot20;
		this.slot21 = slot21;
		this.slot22 = slot22;
		this.slot23 = slot23;
		this.slot24 = slot24;
		this.available = available;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public BigDecimal getBSlotId() {
		return this.BSlotId;
	}

	public void setBSlotId(BigDecimal BSlotId) {
		this.BSlotId = BSlotId;
	}

	public BStatus getBStatus() {
		return this.BStatus;
	}

	public void setBStatus(BStatus BStatus) {
		this.BStatus = BStatus;
	}

	public BGame getBGame() {
		return this.BGame;
	}

	public void setBGame(BGame BGame) {
		this.BGame = BGame;
	}

	public String getSlot1() {
		return this.slot1;
	}

	public void setSlot1(String slot1) {
		this.slot1 = slot1;
	}

	public String getSlot2() {
		return this.slot2;
	}

	public void setSlot2(String slot2) {
		this.slot2 = slot2;
	}

	public String getSlot3() {
		return this.slot3;
	}

	public void setSlot3(String slot3) {
		this.slot3 = slot3;
	}

	public String getSlot4() {
		return this.slot4;
	}

	public void setSlot4(String slot4) {
		this.slot4 = slot4;
	}

	public String getSlot5() {
		return this.slot5;
	}

	public void setSlot5(String slot5) {
		this.slot5 = slot5;
	}

	public String getSlot6() {
		return this.slot6;
	}

	public void setSlot6(String slot6) {
		this.slot6 = slot6;
	}

	public String getSlot7() {
		return this.slot7;
	}

	public void setSlot7(String slot7) {
		this.slot7 = slot7;
	}

	public String getSlot8() {
		return this.slot8;
	}

	public void setSlot8(String slot8) {
		this.slot8 = slot8;
	}

	public String getSlot9() {
		return this.slot9;
	}

	public void setSlot9(String slot9) {
		this.slot9 = slot9;
	}

	public String getSlot10() {
		return this.slot10;
	}

	public void setSlot10(String slot10) {
		this.slot10 = slot10;
	}

	public String getSlot11() {
		return this.slot11;
	}

	public void setSlot11(String slot11) {
		this.slot11 = slot11;
	}

	public String getSlot12() {
		return this.slot12;
	}

	public void setSlot12(String slot12) {
		this.slot12 = slot12;
	}

	public String getSlot13() {
		return this.slot13;
	}

	public void setSlot13(String slot13) {
		this.slot13 = slot13;
	}

	public String getSlot14() {
		return this.slot14;
	}

	public void setSlot14(String slot14) {
		this.slot14 = slot14;
	}

	public String getSlot15() {
		return this.slot15;
	}

	public void setSlot15(String slot15) {
		this.slot15 = slot15;
	}

	public String getSlot16() {
		return this.slot16;
	}

	public void setSlot16(String slot16) {
		this.slot16 = slot16;
	}

	public String getSlot17() {
		return this.slot17;
	}

	public void setSlot17(String slot17) {
		this.slot17 = slot17;
	}

	public String getSlot18() {
		return this.slot18;
	}

	public void setSlot18(String slot18) {
		this.slot18 = slot18;
	}

	public String getSlot19() {
		return this.slot19;
	}

	public void setSlot19(String slot19) {
		this.slot19 = slot19;
	}

	public String getSlot20() {
		return this.slot20;
	}

	public void setSlot20(String slot20) {
		this.slot20 = slot20;
	}

	public String getSlot21() {
		return this.slot21;
	}

	public void setSlot21(String slot21) {
		this.slot21 = slot21;
	}

	public String getSlot22() {
		return this.slot22;
	}

	public void setSlot22(String slot22) {
		this.slot22 = slot22;
	}

	public String getSlot23() {
		return this.slot23;
	}

	public void setSlot23(String slot23) {
		this.slot23 = slot23;
	}

	public String getSlot24() {
		return this.slot24;
	}

	public void setSlot24(String slot24) {
		this.slot24 = slot24;
	}

	public String getAvailable() {
		return this.available;
	}

	public void setAvailable(String available) {
		this.available = available;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
