package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BStatus generated by hbm2java
 */
public class BStatus implements java.io.Serializable {

	private String statusCd;
	private String statusDesc;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;
	private Set BSlots = new HashSet(0);
	private Set BPayments = new HashSet(0);
	private Set BAvailableGameses = new HashSet(0);
	private Set BBookings = new HashSet(0);
	private Set BGames = new HashSet(0);
	private Set BUserses = new HashSet(0);

	public BStatus() {
	}

	public BStatus(String statusCd) {
		this.statusCd = statusCd;
	}

	public BStatus(String statusCd, String statusDesc, Date createdDate, String createdBy, Date updatedDate,
			String updatedBy, Set BSlots, Set BPayments, Set BAvailableGameses, Set BBookings, Set BGames,
			Set BUserses) {
		this.statusCd = statusCd;
		this.statusDesc = statusDesc;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
		this.BSlots = BSlots;
		this.BPayments = BPayments;
		this.BAvailableGameses = BAvailableGameses;
		this.BBookings = BBookings;
		this.BGames = BGames;
		this.BUserses = BUserses;
	}

	public String getStatusCd() {
		return this.statusCd;
	}

	public void setStatusCd(String statusCd) {
		this.statusCd = statusCd;
	}

	public String getStatusDesc() {
		return this.statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Set getBSlots() {
		return this.BSlots;
	}

	public void setBSlots(Set BSlots) {
		this.BSlots = BSlots;
	}

	public Set getBPayments() {
		return this.BPayments;
	}

	public void setBPayments(Set BPayments) {
		this.BPayments = BPayments;
	}

	public Set getBAvailableGameses() {
		return this.BAvailableGameses;
	}

	public void setBAvailableGameses(Set BAvailableGameses) {
		this.BAvailableGameses = BAvailableGameses;
	}

	public Set getBBookings() {
		return this.BBookings;
	}

	public void setBBookings(Set BBookings) {
		this.BBookings = BBookings;
	}

	public Set getBGames() {
		return this.BGames;
	}

	public void setBGames(Set BGames) {
		this.BGames = BGames;
	}

	public Set getBUserses() {
		return this.BUserses;
	}

	public void setBUserses(Set BUserses) {
		this.BUserses = BUserses;
	}

}
