package com.game.bookandplay.service.entities;
// Generated 14 Mar, 2019 10:09:46 PM by Hibernate Tools 5.3.0.Beta2

import java.math.BigDecimal;
import java.util.Date;

/**
 * BUserDetails generated by hbm2java
 */
public class BUserDetails implements java.io.Serializable {

	private BigDecimal BUserDetailsId;
	private BUsers BUsers;
	private String firstname;
	private String lastname;
	private String email;
	private BigDecimal mobile;
	private String gender;
	private Date createdDate;
	private String createdBy;
	private Date updatedDate;
	private String updatedBy;

	public BUserDetails() {
	}

	public BUserDetails(BigDecimal BUserDetailsId) {
		this.BUserDetailsId = BUserDetailsId;
	}

	public BUserDetails(BigDecimal BUserDetailsId, BUsers BUsers, String firstname, String lastname, String email,
			BigDecimal mobile, String gender, Date createdDate, String createdBy, Date updatedDate, String updatedBy) {
		this.BUserDetailsId = BUserDetailsId;
		this.BUsers = BUsers;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.mobile = mobile;
		this.gender = gender;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updatedDate = updatedDate;
		this.updatedBy = updatedBy;
	}

	public BigDecimal getBUserDetailsId() {
		return this.BUserDetailsId;
	}

	public void setBUserDetailsId(BigDecimal BUserDetailsId) {
		this.BUserDetailsId = BUserDetailsId;
	}

	public BUsers getBUsers() {
		return this.BUsers;
	}

	public void setBUsers(BUsers BUsers) {
		this.BUsers = BUsers;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public BigDecimal getMobile() {
		return this.mobile;
	}

	public void setMobile(BigDecimal mobile) {
		this.mobile = mobile;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

}
